In [1]:
import utils
import pandas as pd

In [2]:
_, _, _, transition = utils.upload_data()

The following code deminstrates the manipulations damn

In [3]:
transition

         AAA     AA      A    BBB     BB      B  CCC/C    Def     NR
AAA    87.06   9.06   0.53   0.05   0.11   0.03   0.05   0.00   3.11
AA      0.48  87.23   7.77   0.47   0.05   0.06   0.02   0.02   3.89
A       0.03   1.60  88.58   5.00   0.26   0.11   0.02   0.05   4.35
BBB     0.00   0.09   3.25  86.49   3.56   0.43   0.10   0.16   5.92
BB      0.01   0.03   0.11   4.55  77.82   6.80   0.55   0.63   9.51
B       0.00   0.02   0.07   0.15   4.54  74.60   4.96   3.34  12.33
CCC/C   0.00   0.00   0.10   0.17   0.55  12.47  43.11  28.30  15.31

In [4]:
utils.change_TM(transition)

/Users/rickyyung/MFM 714 project/MFM-714-Project/utils.py:220: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  da_new_2 =  matrix * np.reciprocal(np.sum(matrix,axis=1)[:,np.newaxis])
/Users/rickyyung/MFM 714 project/MFM-714-Project/utils.py:227: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  adjustment=da_new * missing[:,None]

,AAA,AA,A,BBB,BB,B,CCC/C,Def
AAA,89.514964,9.349845,0.546956,0.330237,0.113519,0.082559,0.051600,0.010320
AA,0.499480,90.546328,8.085328,0.489074,0.275732,0.062435,0.020812,0.020812
A,0.031364,1.672765,92.608468,5.227392,0.271824,0.115003,0.020910,0.052274
BBB,0.000000,0.095663,3.454507,91.932398,3.784014,0.457058,0.106293,0.170068
BB,0.011050,0.033149,0.121547,5.027624,85.988950,7.513812,0.607735,0.696133
B,0.000000,0.022810,0.079836,0.171077,5.177920,85.082117,5.656934,3.809307
CCC/C,0.000000,0.000000,0.118064,0.200708,0.649351,14.722550,50.897285,33.412043